### ISSUE TITLE
Build 0.26_..._0 appears to be broken

### ISSUE THREAD

**Issue by AlexTate** [conda-forge/cwl-utils-feedstock#13]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Build 0.26\_...\_0 doesn't list urllib3 as a dependency
Build 0.26\_...\_1 requires urllib3 <2

If build 0.26\_...\_0 is installed as a `cwltool` dependency, the following exception is raised when it is invoked from the commandline:
```
Traceback (most recent call last):
  File "/Users/user/miniconda3/envs/cwltool-env/bin/cwltool", line 11, in <module>
    sys.exit(run())
  File "cwltool/main.py", line 1447, in run
  File "cwltool/main.py", line 1022, in main
  File "cwltool/utils.py", line 117, in versionstring
  File "/Users/user/miniconda3/envs/cwltool-env/lib/python3.10/site-packages/pkg_resources/__init__.py", line 966, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/user/miniconda3/envs/cwltool-env/lib/python3.10/site-packages/pkg_resources/__init__.py", line 827, in resolve
    dist = self._resolve_dist(
  File "/Users/user/miniconda3/envs/cwltool-env/lib/python3.10/site-packages/pkg_resources/__init__.py", line 873, in _resolve_dist
    raise VersionConflict(dist, req).with_context(dependent_req)

pkg_resources.ContextualVersionConflict: (urllib3 2.0.2 (/Users/alex/miniconda3/envs/cwltool/lib/python3.9/site-packages), Requirement.parse('urllib3<2'), {'cwl-utils', 'schema-salad'})
```

Steps to reproduce the issue:
```
mamba create -n cwltool-env -c conda-forge python=3.10 cwltool
mamba activate cwltool-env
cwltool
```

### Installed packages

```shell
# packages in environment at /Users/user/miniconda3/envs/cwltool-env:
#
# Name                    Version                   Build  Channel
argcomplete               3.0.8              pyhd8ed1ab_0    conda-forge
atk-1.0                   2.38.0               h1d18e73_1    conda-forge
bagit                     1.8.1              pyhd8ed1ab_0    conda-forge
black                     23.3.0          py310h2ec42d9_1    conda-forge
bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
boltons                   23.0.0             pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                hb7f2c08_8    conda-forge
brotli-bin                1.0.9                hb7f2c08_8    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
ca-certificates           2023.5.7             h8857fd0_0    conda-forge
cachecontrol              0.12.11            pyhd8ed1ab_1    conda-forge
cairo                     1.16.0            h09dd18c_1016    conda-forge
certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310ha78151a_3    conda-forge
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
cheetah3                  3.2.6.post2     py310h90acd4f_3    conda-forge
click                     8.1.3           py310h2ec42d9_1    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
coloredlogs               15.0.1          py310h2ec42d9_2    conda-forge
conda                     23.3.1          py310h2ec42d9_0    conda-forge
conda-package-handling    2.0.2              pyh38be061_0    conda-forge
conda-package-streaming   0.7.0              pyhd8ed1ab_1    conda-forge
cryptography              40.0.2          py310hdd0c95c_0    conda-forge
cwl-upgrader              1.2.6              pyhd8ed1ab_0    conda-forge
cwl-utils                 0.26               pyh1d7be83_0    conda-forge
cwlformat                 2022.02.18         pyhd8ed1ab_0    conda-forge
cwltool                   3.1.20230425144158 py310h2f27fe4_0    conda-forge
docutils                  0.20.1          py310h2ec42d9_0    conda-forge
expat                     2.5.0                hf0c8a7f_1    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h5bb23bf_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               h3f81eb7_1    conda-forge
fribidi                   1.0.10               hbcb3906_0    conda-forge
future                    0.18.3             pyhd8ed1ab_0    conda-forge
galaxy-containers         22.1.1             pyhd8ed1ab_0    conda-forge
galaxy-tool-util          22.1.5             pyhd8ed1ab_0    conda-forge
galaxy-util               22.1.1             pyhd8ed1ab_0    conda-forge
gdk-pixbuf                2.42.10              hff535ac_2    conda-forge
gettext                   0.21.1               h8a4c099_0    conda-forge
giflib                    5.2.1                hb7f2c08_3    conda-forge
gmp                       6.2.1                h2e338ed_0    conda-forge
graphite2                 1.3.14               he9d5cce_1  
graphviz                  2.50.0               ha5baa68_3    conda-forge
gtk2                      2.24.33              h7c1209e_2    conda-forge
gts                       0.7.6                hccb3bdf_2    conda-forge
harfbuzz                  7.3.0                h413ba03_0    conda-forge
humanfriendly             10.0            py310h2ec42d9_4    conda-forge
icu                       72.1                 h7336db1_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        6.6.0              pyha770c72_0    conda-forge
importlib_resources       5.12.0             pyhd8ed1ab_0    conda-forge
isodate                   0.6.1              pyhd8ed1ab_0    conda-forge
jsonpatch                 1.32               pyhd8ed1ab_0    conda-forge
jsonpointer               2.1                pyhd3eb1b0_0  
lerc                      4.0.0                hb486fe8_0    conda-forge
libbrotlicommon           1.0.9                hb7f2c08_8    conda-forge
libbrotlidec              1.0.9                hb7f2c08_8    conda-forge
libbrotlienc              1.0.9                hb7f2c08_8    conda-forge
libcxx                    16.0.4               hd57cbcb_0    conda-forge
libdeflate                1.18                 hac1461d_0    conda-forge
libexpat                  2.5.0                hf0c8a7f_1    conda-forge
libffi                    3.4.4                hecd8cb5_0  
libgd                     2.3.3                h3d994df_6    conda-forge
libglib                   2.76.2               hc62aa5d_0    conda-forge
libiconv                  1.17                 hac89ed1_0    conda-forge
libjpeg-turbo             2.1.5.1              hb7f2c08_0    conda-forge
libpng                    1.6.39               ha978bb4_0    conda-forge
librsvg                   2.56.0               h123f2dd_0    conda-forge
libsqlite                 3.42.0               h58db7d2_0    conda-forge
libtiff                   4.5.0                hedf67fa_6    conda-forge
libtool                   2.4.7                hf0c8a7f_0    conda-forge
libwebp                   1.3.0                ha9aa8fa_0    conda-forge
libwebp-base              1.3.0                hb7f2c08_0    conda-forge
libxml2                   2.10.4               h554bb67_0    conda-forge
libxslt                   1.1.37               h5d22bc9_0    conda-forge
libzlib                   1.2.13               hfd90126_4    conda-forge
lockfile                  0.12.2                     py_1    conda-forge
lxml                      4.9.2           py310h0b20c97_0    conda-forge
lz4-c                     1.9.4                hf0c8a7f_0    conda-forge
markupsafe                2.1.2           py310h90acd4f_0    conda-forge
mistune                   2.0.5              pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.5           py310ha23aa8a_0    conda-forge
mypy_extensions           1.0.0              pyha770c72_0    conda-forge
ncurses                   6.4                  hcec6c5f_0  
networkx                  3.1                pyhd8ed1ab_0    conda-forge
openssl                   3.1.0                h8a1eda9_3    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pango                     1.50.14              hbce5e75_1    conda-forge
pathspec                  0.11.1             pyhd8ed1ab_0    conda-forge
pcre2                     10.40                h1c4e4bc_0    conda-forge
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               hbcb3906_0    conda-forge
platformdirs              3.5.1              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0           py310h2ec42d9_4    conda-forge
prov                      1.5.1                      py_1    conda-forge
psutil                    5.9.5           py310h90acd4f_0    conda-forge
pycosat                   0.6.4           py310h90acd4f_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pycryptodome              3.18.0          py310h7e2be6d_0    conda-forge
pydantic                  1.10.7          py310h90acd4f_0    conda-forge
pydot                     1.4.2           py310h2ec42d9_3    conda-forge
pydotplus                 2.0.2              pyhaef67bd_5    conda-forge
pyopenssl                 23.1.1             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1           py310h2ec42d9_5    conda-forge
python                    3.10.11         he7542f4_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    3_cp310    conda-forge
pyyaml                    6.0             py310h90acd4f_5    conda-forge
rdflib                    6.3.2              pyhd8ed1ab_0    conda-forge
readline                  8.2                  h9e318b2_1    conda-forge
repoze.lru                0.7                        py_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
routes                    2.5.1              pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.17.21         py310h90acd4f_3    conda-forge
ruamel.yaml.clib          0.2.7           py310h90acd4f_1    conda-forge
schema-salad              8.4.20230511084951 py310h6729b98_0    conda-forge
setuptools                67.7.2             pyhd8ed1ab_0    conda-forge
shellescape               3.4.1                      py_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
typing-extensions         4.5.0                hd8ed1ab_0    conda-forge
typing_extensions         4.5.0              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   2.0.2              pyhd8ed1ab_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
whoosh                    2.7.4           py310h2ec42d9_7    conda-forge
xz                        5.4.2                h6c40b1e_0  
yaml                      0.2.5                h0d85af4_2    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zipstream-new             1.1.8              pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hfd90126_4    conda-forge
zstandard                 0.19.0          py310h3cf44b0_1    conda-forge
zstd                      1.5.5                hc035e20_0
```

### Environment info

```shell
active environment : cwltool-env
    active env location : /Users/user/miniconda3/envs/cwltool-env
            shell level : 2
       user config file : /Users/user/.condarc
 populated config files : /Users/user/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.11.final.0
       virtual packages : __archspec=1=x86_64
                          __osx=10.16=0
                          __unix=0=0
       base environment : /Users/user/miniconda3  (writable)
      conda av data dir : /Users/user/miniconda3/envs/environment/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /private/var/folders/jn/1q8q_1nn14918cyptvmlhw0h0000gn/T/tmp.K0p1UyRI
       envs directories : /Users/user/miniconda3/envs
                          /Users/user/.conda/envs
               platform : osx-64
             user-agent : conda/23.3.1 requests/2.31.0 CPython/3.10.11 Darwin/20.6.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by mr-c** [comment]
@AlexTate Does the recent builds fix your issue?
